import React, { createContext, useState, ReactNode, useContext, useEffect } from 'react';

type Language = 'English' | 'Français' | 'Deutsch' | 'Español' | '中文';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  langCode: string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const LANGUAGE_CODES: Record<Language, string> = {
  'English': 'en',
  'Français': 'fr',
  'Deutsch': 'de',
  'Español': 'es',
  '中文': 'zh'
};

// Simple Translation Dictionary
const TRANSLATIONS: Record<string, Record<string, string>> = {
  'en': {
    'Today': 'Today',
    'Field': 'Field',
    'Learn': 'Learn',
    'Upcoming': 'Upcoming',
    'Settings': 'Settings',
    'Planetary Field': 'Planetary Field',
    'Daily Echoes': 'Daily Echoes',
    'Calendar Systems': 'Calendar Systems',
    'Artifact of the Day': 'Artifact of the Day',
    'Living Calendar': 'Living Calendar',
    'Saved': 'Saved',
    'No cultural offering surfaced today.': 'No cultural offering surfaced today.',
    'The field is quiet here. Try again later.': 'The field is quiet here. Try again later.',
    'Refresh': 'Refresh',
    'Use Current Location': 'Use Current Location',
    'Display': 'Display',
    'Language': 'Language',
    'Theme': 'Theme',
    'Privacy': 'Privacy',
    'No accounts. Preferences stored on-device.': 'No accounts. Preferences stored on-device.',
    'Set Location': 'Set Location',
    'Cancel': 'Cancel',
    'Select Language': 'Select Language',
    'Select Theme': 'Select Theme',
    'Close': 'Close',
    'Soon': 'Soon',
    'Cycle': 'Cycle',
    'Season': 'Season',
    'Timing Windows': 'Timing Windows',
    'Lunar & Planetary Milestones': 'Lunar & Planetary Milestones',
    'Seasonal Turning Points': 'Seasonal Turning Points',
    'All': 'All',
    'Astronomical': 'Astronomical',
    'Cultural': 'Cultural',
    'Next 48 hours': 'Next 48 hours',
    'Next 14 days': 'Next 14 days',
    'Next 90 days': 'Next 90 days',
    'Events & Moments': 'Events & Moments',
    'Cosmos': 'Cosmos',
    'Earth': 'Earth',
    'Body': 'Body',
    'Solar': 'Solar',
    'Lunar': 'Lunar',
    'Geomagnetic': 'Geomagnetic',
    'Seasonal': 'Seasonal',
    'Atmosphere': 'Atmosphere',
    'Schumann Resonance': 'Schumann Resonance',
    'Circadian Rhythm': 'Circadian Rhythm',
    'Data Sources': 'Data Sources',
    'Live': 'Live',
    'Model': 'Model',
    'Static': 'Static',
    'Rotate lens': 'Rotate lens',
    'Today in this system': 'Today in this system',
    'Living Rhythm': 'Living Rhythm',
    'Carry into Quiet Frame': 'Carry into Quiet Frame'
  },
  'fr': {
    'Today': 'Aujourd\'hui',
    'Field': 'Champ',
    'Learn': 'Apprendre',
    'Upcoming': 'À venir',
    'Settings': 'Paramètres',
    'Planetary Field': 'Champ Planétaire',
    'Daily Echoes': 'Échos Quotidiens',
    'Calendar Systems': 'Systèmes Calendaires',
    'Artifact of the Day': 'Artefact du Jour',
    'Living Calendar': 'Calendrier Vivant',
    'Saved': 'Enregistré',
    'No cultural offering surfaced today.': 'Aucune offre culturelle aujourd\'hui.',
    'The field is quiet here. Try again later.': 'Le champ est calme ici. Réessayez plus tard.',
    'Refresh': 'Actualiser',
    'Use Current Location': 'Utiliser la position actuelle',
    'Display': 'Affichage',
    'Language': 'Langue',
    'Theme': 'Thème',
    'Privacy': 'Confidentialité',
    'No accounts. Preferences stored on-device.': 'Pas de comptes. Préférences stockées sur l\'appareil.',
    'Set Location': 'Définir le lieu',
    'Cancel': 'Annuler',
    'Select Language': 'Choisir la langue',
    'Select Theme': 'Choisir le thème',
    'Close': 'Fermer',
    'Soon': 'Bientôt',
    'Cycle': 'Cycle',
    'Season': 'Saison',
    'Timing Windows': 'Fenêtres Temporelles',
    'Lunar & Planetary Milestones': 'Jalons Lunaires et Planétaires',
    'Seasonal Turning Points': 'Tournants Saisonniers',
    'All': 'Tout',
    'Astronomical': 'Astronomique',
    'Cultural': 'Culturel',
    'Next 48 hours': 'Prochaines 48 heures',
    'Next 14 days': 'Prochains 14 jours',
    'Next 90 days': 'Prochains 90 jours',
    'Events & Moments': 'Événements et Moments',
    'Cosmos': 'Cosmos',
    'Earth': 'Terre',
    'Body': 'Corps',
    'Solar': 'Solaire',
    'Lunar': 'Lunaire',
    'Geomagnetic': 'Géomagnétique',
    'Seasonal': 'Saisonnier',
    'Atmosphere': 'Atmosphère',
    'Schumann Resonance': 'Résonance de Schumann',
    'Circadian Rhythm': 'Rythme Circadien',
    'Data Sources': 'Sources de Données',
    'Live': 'Direct',
    'Model': 'Modèle',
    'Static': 'Statique',
    'Rotate lens': 'Tourner la lentille',
    'Today in this system': 'Aujourd\'hui dans ce système',
    'Living Rhythm': 'Rythme Vivant',
    'Carry into Quiet Frame': 'Porter dans le Cadre Calme'
  },
  'de': {
    'Today': 'Heute',
    'Field': 'Feld',
    'Learn': 'Lernen',
    'Upcoming': 'Demnächst',
    'Settings': 'Einstellungen',
    'Planetary Field': 'Planetares Feld',
    'Daily Echoes': 'Tägliche Echos',
    'Calendar Systems': 'Kalendersysteme',
    'Artifact of the Day': 'Artefakt des Tages',
    'Living Calendar': 'Lebendiger Kalender',
    'Saved': 'Gespeichert',
    'No cultural offering surfaced today.': 'Kein kulturelles Angebot heute aufgetaucht.',
    'The field is quiet here. Try again later.': 'Das Feld ist hier ruhig. Versuchen Sie es später erneut.',
    'Refresh': 'Aktualisieren',
    'Use Current Location': 'Aktuellen Standort verwenden',
    'Display': 'Anzeige',
    'Language': 'Sprache',
    'Theme': 'Thema',
    'Privacy': 'Datenschutz',
    'No accounts. Preferences stored on-device.': 'Keine Konten. Einstellungen auf dem Gerät gespeichert.',
    'Set Location': 'Standort festlegen',
    'Cancel': 'Abbrechen',
    'Select Language': 'Sprache auswählen',
    'Select Theme': 'Thema auswählen',
    'Close': 'Schließen',
    'Soon': 'Bald',
    'Cycle': 'Zyklus',
    'Season': 'Saison',
    'Timing Windows': 'Zeitfenster',
    'Lunar & Planetary Milestones': 'Mond- & Planetenmeilensteine',
    'Seasonal Turning Points': 'Saisonale Wendepunkte',
    'All': 'Alle',
    'Astronomical': 'Astronomisch',
    'Cultural': 'Kulturell',
    'Next 48 hours': 'Nächste 48 Stunden',
    'Next 14 days': 'Nächste 14 Tage',
    'Next 90 days': 'Nächste 90 Tage',
    'Events & Moments': 'Ereignisse & Momente',
    'Cosmos': 'Kosmos',
    'Earth': 'Erde',
    'Body': 'Körper',
    'Solar': 'Solar',
    'Lunar': 'Lunar',
    'Geomagnetic': 'Geomagnetisch',
    'Seasonal': 'Saisonal',
    'Atmosphere': 'Atmosphäre',
    'Schumann Resonance': 'Schumann-Resonanz',
    'Circadian Rhythm': 'Zirkadianer Rhythmus',
    'Data Sources': 'Datenquellen',
    'Live': 'Live',
    'Model': 'Modell',
    'Static': 'Statisch',
    'Rotate lens': 'Linse drehen',
    'Today in this system': 'Heute in diesem System',
    'Living Rhythm': 'Lebendiger Rhythmus',
    'Carry into Quiet Frame': 'In den Stillen Rahmen tragen'
  },
  'es': {
    'Today': 'Hoy',
    'Field': 'Campo',
    'Learn': 'Aprender',
    'Upcoming': 'Próximo',
    'Settings': 'Ajustes',
    'Planetary Field': 'Campo Planetario',
    'Daily Echoes': 'Ecos Diarios',
    'Calendar Systems': 'Sistemas de Calendario',
    'Artifact of the Day': 'Artefacto del Día',
    'Living Calendar': 'Calendario Vivo',
    'Saved': 'Guardado',
    'No cultural offering surfaced today.': 'Ninguna oferta cultural surgió hoy.',
    'The field is quiet here. Try again later.': 'El campo está tranquilo aquí. Inténtalo de nuevo más tarde.',
    'Refresh': 'Actualizar',
    'Use Current Location': 'Usar ubicación actual',
    'Display': 'Pantalla',
    'Language': 'Idioma',
    'Theme': 'Tema',
    'Privacy': 'Privacidad',
    'No accounts. Preferences stored on-device.': 'Sin cuentas. Preferencias guardadas en el dispositivo.',
    'Set Location': 'Establecer ubicación',
    'Cancel': 'Cancelar',
    'Select Language': 'Seleccionar idioma',
    'Select Theme': 'Seleccionar tema',
    'Close': 'Cerrar',
    'Soon': 'Pronto',
    'Cycle': 'Ciclo',
    'Season': 'Temporada',
    'Timing Windows': 'Ventanas de Tiempo',
    'Lunar & Planetary Milestones': 'Hitos Lunares y Planetarios',
    'Seasonal Turning Points': 'Puntos de Inflexión Estacionales',
    'All': 'Todo',
    'Astronomical': 'Astronómico',
    'Cultural': 'Cultural',
    'Next 48 hours': 'Próximas 48 horas',
    'Next 14 days': 'Próximos 14 días',
    'Next 90 days': 'Próximos 90 días',
    'Events & Moments': 'Eventos y Momentos',
    'Cosmos': 'Cosmos',
    'Earth': 'Tierra',
    'Body': 'Cuerpo',
    'Solar': 'Solar',
    'Lunar': 'Lunar',
    'Geomagnetic': 'Geomagnético',
    'Seasonal': 'Estacional',
    'Atmosphere': 'Atmósfera',
    'Schumann Resonance': 'Resonancia Schumann',
    'Circadian Rhythm': 'Ritmo Circadiano',
    'Data Sources': 'Fuentes de Datos',
    'Live': 'En vivo',
    'Model': 'Modelo',
    'Static': 'Estático',
    'Rotate lens': 'Girar lente',
    'Today in this system': 'Hoy en este sistema',
    'Living Rhythm': 'Ritmo Vivo',
    'Carry into Quiet Frame': 'Llevar al Marco Tranquilo'
  },
  '中文': {
    'Today': '今天',
    'Field': '场域',
    'Learn': '探索',
    'Upcoming': '即将到来',
    'Settings': '设置',
    'Planetary Field': '行星场域',
    'Daily Echoes': '每日回响',
    'Calendar Systems': '历法系统',
    'Artifact of the Day': '今日文物',
    'Living Calendar': '鲜活历法',
    'Saved': '已保存',
    'No cultural offering surfaced today.': '今天没有文化内容浮现。',
    'The field is quiet here. Try again later.': '此地场域平静。请稍后再试。',
    'Refresh': '刷新',
    'Use Current Location': '使用当前位置',
    'Display': '显示',
    'Language': '语言',
    'Theme': '主题',
    'Privacy': '隐私',
    'No accounts. Preferences stored on-device.': '无账户。偏好设置存储在设备上。',
    'Set Location': '设置位置',
    'Cancel': '取消',
    'Select Language': '选择语言',
    'Select Theme': '选择主题',
    'Close': '关闭',
    'Soon': '近期',
    'Cycle': '周期',
    'Season': '季节',
    'Timing Windows': '时间窗口',
    'Lunar & Planetary Milestones': '月球与行星里程碑',
    'Seasonal Turning Points': '季节转折点',
    'All': '全部',
    'Astronomical': '天文',
    'Cultural': '文化',
    'Next 48 hours': '未来48小时',
    'Next 14 days': '未来14天',
    'Next 90 days': '未来90天',
    'Events & Moments': '事件与时刻',
    'Cosmos': '宇宙',
    'Earth': '地球',
    'Body': '身体',
    'Solar': '太阳',
    'Lunar': '月亮',
    'Geomagnetic': '地磁',
    'Seasonal': '季节性',
    'Atmosphere': '大气',
    'Schumann Resonance': '舒曼共振',
    'Circadian Rhythm': '昼夜节律',
    'Data Sources': '数据来源',
    'Live': '实时',
    'Model': '模型',
    'Static': '静态',
    'Rotate lens': '旋转视角',
    'Today in this system': '今日历法',
    'Living Rhythm': '鲜活节律',
    'Carry into Quiet Frame': '带入静谧框架'
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('English');

  const t = (key: string) => {
    const langCode = LANGUAGE_CODES[language];
    return TRANSLATIONS[langCode]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, langCode: LANGUAGE_CODES[language] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}